### ISSUE TITLE
Blank `modified_time` from package analysis project import

### ISSUE THREAD

**Issue by maxfisher-g** [ossf/malicious-packages#120]
I noticed that a malware report for [eslint-plugin-dropbox-sign]( https://github.com/ossf/malicious-packages/blob/main/malicious/npm/eslint-plugin-dropbox-sign/MAL-2023-4.json) contains `"modified_time": "0001-01-01T00:00:00Z"` in a `malicious-package-origins` entry.

Is this normal/intended?

**Comment by calebbrown** [comment]
This was not intended, and a result of my work fixing the source ID of `ossf-package-analysis`.

This doesn't present a problem at the moment, but it is not ideal.

**Comment by calebbrown** [comment]
Scanning the repository indicates that this is only a problem with that specific OSV report.

I will fix it manually.
