### ISSUE TITLE
Ranges on MAL-2023-8697 not updated to reflect GHSA 

### ISSUE THREAD

**Issue by oliverchang** [ossf/malicious-packages#458]
https://github.com/ossf/malicious-packages/blob/cb2451689cd5b89457d1e135c8bfe538d8252dc0/osv/malicious/npm/%40ledgerhq/connect-kit/MAL-2023-8697.json#L9 doesn't seem to have updated to reflect the new ranges on https://github.com/advisories/GHSA-g9hp-hq3h-h6hx, which now constrains the range to >= 1.1.5, <= 1.1.7.

It seems like either (or both):
- The GHSA importer doesn't update existing MAL entries when the GHSA entry is updated. 
- The OSV converter doesn't support `last_affected` conversions.

**Comment by calebbrown** [comment]
See https://github.com/ossf/osv-schema/pull/239
