### ISSUE TITLE
Remove MAL-2024-10183 advisory

### ISSUE THREAD

**Issue by mgdcvetko** [ossf/malicious-packages#703]
Hi, 

we found an issue in one of our reports which is reflected in the MAL-2024-10183 advisory. We created the report for a package named `urlcon-` which is incorrect, the name is just `urlcon` (without the trailing dash). We suggest withdrawing the mentioned advisory as there is now a new, correct one named MAL-2024-11737. Can I open the PR for withdrawing the old advisory, or is this something OSSF handles?

We would also like to apologize for this issue, we are developing a plan to implement more checks in our processes to try and catch this kind of mistake earlier.

Mentioning @rhalar for visibility.

**Comment by calebbrown** [comment]
Please open a PR with the change.

To withdraw the following steps are required:

1. move the report into the correct withdrawn location
2. add a "withdrawn" timestamp
3. update the "modified" timestamp
